### ISSUE TITLE
RFC5424 formatter does not generate the STRUCTURED-DATA field

### ISSUE THREAD

**Issue by bluttringer** [RackSec/srslog#23]
The RFC says the syslog format is (according to the syslog-ng doc):
`HEADER STRUCTURED-DATA MSG`

A sample could be 
```
<34>1 2003-10-11T22:14:15.003Z mymachine.example.com su - ID47 - BOM'su root' failed for lonvick on /dev/pts/8
```
that corresponds to the following format 
```
<priority>VERSION ISOTIMESTAMP HOSTNAME APPLICATION PID MESSAGEID STRUCTURED-DATA MSG
```
(ref: https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/concepts-message-ietfsyslog.html)

The RFC documentation (from IETF)  says:
```
STRUCTURED-DATA provides a mechanism to express information in a well
defined, easily parseable and interpretable data format.  There are
multiple usage scenarios.  For example, it may express meta-
information about the syslog message or application-specific
information such as traffic counters or IP addresses.

STRUCTURED-DATA can contain zero, one, or multiple structured data
elements, which are referred to as "SD-ELEMENT" in this document.

In case of zero structured data elements, the STRUCTURED-DATA field
MUST contain the NILVALUE.
```
(ref: https://tools.ietf.org/html/rfc5424#section-6.3)

In our case, the best would be to add an hyphen (that is the NILVALUE indicated by the RFC) between the HEADER and the MESSAGE.

What do you think?

**Comment by sirsean** [comment]
_This_ issue is resolved in #24 by adding the `-` to adhere to the 5424 spec.

Actually adding support for including structured data will require an interface change. We'll have to figure out how we want to do that!
